language: python
python:
    - "3.4"
    - "3.3"
    - "3.2"
before_install:
    - pip install -r dev_requirements.txt
script:
    - .githooks/pre-commit -f
    - ./runtests.sh
deploy:
    provider: pypi
    user: ixa
    password:
        secure: KotqwXcFnooWKlSp1jM98898loE9ugWpba7tXGcDFuHhXQGT/wXtNgzROa2EhPxs7IYfQtxq4HD3dadYSziuUzHRTTjg5YUiW9Gx4N0gFtfthraroKu4IB62B9k84YPmxIIZZNvkJOSd1Ip5x2/+TJntPcroi0UK4GFRhLmcOKM=
    server: https://pypi.python.org/pypi
    on:
        branch: release
        python: 3.3
