language: python
python:
    - "3.3"
    - "3.2"
before_install:
    - npm install jshint
    - pip install pep8 pylint pylint_mccabe
    - pip install pyxdg pyyaml
script:
    - .githooks/pre-commit -f
    - python setup.py test
